---
jenkins_auth_realm:
  name: unix
  service: su
  plain_password: jenkins
  crypted_password: $6$rAVyI.p2wXVDKk5w$y0G1MQehmHtvaPgdtbrnvAsBqYQ99g939vxrdLXtPQCh/e7GJVwbnqIKZpve8EcMLTtq.7sZwTBYV9Tdjgf1k.
# This a path to a file containing jenkins credentials, as these credenials
# would be used to access a production systems, this file is not checked in
# to this repository.
# See readme for example
jenkins_credentials_file:  files/ansible-jenkins-credentials.yaml
jenkins_connection_retries: 20
jenkins_connection_delay: 0.5


