---

# See Readme.md for variable descriptions

jenkins_credentials_file:  files/ansible-jenkins-credentials.json
jenkins_connection_retries: 60
jenkins_connection_delay: 0.5
jenkins_auth_realm:
  name: unix
  service: su
  plain_password: jenkins
  crypted_password: $6$rAVyI.p2wXVDKk5w$y0G1MQehmHtvaPgdtbrnvAsBqYQ99g939vxrdLXtPQCh/e7GJVwbnqIKZpve8EcMLTtq.7sZwTBYV9Tdjgf1k.

# To include provisioning many seed jobs you'd need to use
# Ansible 2.0+, and then include + with_items that was re-introduced then
jenkins_seed_job:
  name: seed
  time_trigger: "H * * * *"
  removed_job_action: "DELETE"
  removed_view_action: "IGNORE"
  scm:
    type: git
    url: "git@github.com:edx-ops/edx-jenkins-job-dsl.git"
    credential_id: "github-deploy-key"
    target_jobs: "jobs/analytics-edx-jenkins.edx.org/*Jobs.groovy"
    additional_classpath: "src/main/groovy"






