# Installs packages to run edx locally on a single instance, and creates necessary databases and users
#
---

- name: install packages needed for single server
  apt: pkg={{ item }} install_recommends=yes state=present
  with_items: edxlocal_debian_pkgs

# TODO: Add a test to make sure mysql is running.

- include: databases.yml
  when: EDXAPP_MYSQL_HOST == 'localhost'

- name: install memcached
  apt: pkg=memcached state=present
