---
dependencies:
  - common
  - supervisor
  - edxapp_common
  - devpi
  - nltk
  - role: user
    user_info:
      - name: "{{ EDXAPP_AUTOMATOR_NAME }}"
        sudo_cmds: "{{ EDXAPP_AUTOMATOR_SUDO_CMDS }}"
        type: restricted
        authorized_keys: "{{ EDXAPP_AUTOMATOR_AUTHORIZED_KEYS }}"
    when: EDXAPP_AUTOMATOR_AUTHORIZED_KEYS|length != 0
