- name: Add script for syncing logs on exit
  template:
    src: sync-logs-on-exit.j2
    dest: "{{ COMMON_BIN_DIR }}/sync-logs-on-exit"
    owner: root
    group: root
    mode: 0744

- name: Force logrotate on syslog stop
  lineinfile:
    path: /etc/systemd/system/syslog.service
    line: "ExecStop={{ COMMON_OBJECT_STORE_LOG_SYNC_ON_EXIT }}"
    insertafter: "^ExecStart=.*$"
