---
# TODO: Remove the yaml dependency, Java seems to have
# json parser built in, and converting these formats on
# the fly would be a better solution
- set_fact:
    jenkins_credentials_root: '/tmp/credentials'
- set_fact:
    jenkins_credentials_file_dest: "{{ jenkins_credentials_root }}/credentials.yaml"
    jenkins_credentials_script: "{{ jenkins_credentials_root }}/addCredentials.groovy"
- name: create credentials dir
  file: name={{ jenkins_credentials_root }} state=directory
- name: upload snakeyml to remote server
  get_url:
    url=http://central.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar
    dest=/var/cache/jenkins/war/WEB-INF/lib/snakeyaml-1.17.jar
    sha256sum=5666b36f9db46f06dd5a19d73bbff3b588d5969c0f4b8848fde0f5ec849430a5
  register: out
# We need to restart jenkins before script is executed, handlers would need to
# wait for
- name: restart jenkins now
  service: name=jenkins state=restarted
  when: out.changed
- name: upload groovy scipt
  template: src=addCredentials.groovy dest={{jenkins_credentials_script}}
        mode="600"
- name: upload credentials file
  copy: src={{ jenkins_credentials_file }} dest={{ jenkins_credentials_file_dest }}
        mode="600"
        owner={{jenkins_user}}
- name: add credentials
  include: _execute_ansible_cli.yaml
  vars:
    jenkins_command_string: "groovy {{ jenkins_credentials_script }}"
- name: clean up
  file: name={{ jenkins_credentials_root }} state=absent

