---
# TODO: Remove the yaml dependency, Java seems to have
# json parser built in, and converting these formats on
# the fly would be a better solution
- set_fact:
    jenkins_credentials_root: '/tmp/credentials'
- set_fact:
    jenkins_credentials_file_dest: "{{ jenkins_credentials_root }}/credentials.yaml"
    jenkins_credentials_script: "{{ jenkins_credentials_root }}/addCredentials.groovy"
- name: create credentials dir
  file: name={{ jenkins_credentials_root }} state=directory
- name: upload groovy scipt
  template: src=addCredentials.groovy dest={{jenkins_credentials_script}}
        mode="600"
- name: upload credentials file
  copy: src={{ jenkins_credentials_file }} dest={{ jenkins_credentials_file_dest }}
        mode="600"
        owner={{jenkins_user}}
- name: add credentials
  include: _execute_ansible_cli.yaml
  vars:
    jenkins_command_string: "groovy {{ jenkins_credentials_script }}"
- name: clean up
  file: name={{ jenkins_credentials_root }} state=absent

