---
# Jenkins is started by the trigger of jenkins_master job, which trigger
# is executed after whole playbook. Since we expect Jenkins running
# force it to be started now
- name: start jenkins now
  service: name=jenkins state=started
- include: _auth_realm.yaml
# TODO: Remove me it checks whether cli works
#- include: _execute_ansible_cli.yaml
#  vars:
#    jenkins_command_string: "who-am-i"
#- debug: var=jenkins_command_output
- include: _add_credentials.yaml
- name: create seed jobs
  include: _create_seed_job.yaml
  vars:
    job_name: "{{ jenkins_seed_job.name }}"
    job: "{{ jenkins_seed_job }}"

