---

- fail: msg=included unix realm by accident
  when: jenkins_auth_realm.name != "unix"

- fail: msg=Please change default password for jenkins user
  when: jenkins_auth_realm.plain_password == 'jenkins'

- user:
    name: "{{ jenkins_user }}"
    groups: shadow
    append: yes
    password: "{{ jenkins_auth_realm.hashed_password }}"
    update_password: always

- name: template config.xml
  template:
    src: jenkins.config.main.xml
    dest: "{{ jenkins_home }}/config.xml"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"

# Unconditionally restart Jenkins, this has two side-effects:
# 1. Jenkins uses new auth realm
# 2. We guarantee that jenkins is started (this is not certain
#    as Jenkins is started by handlers from jenkins_master,
#    these handlers are launched after this role).

- name: restart Jenkins
  service: name=jenkins state=restarted

# Upload Jenkins credentials

- name: create credentials dir
  file: name={{ jenkins_credentials_root }} state=directory

- name: upload groovy script
  template:
    src: addCredentials.groovy
    dest: "{{ jenkins_credentials_script }}"
    mode: "600"

- name: upload credentials file
  template:
    src: credentials_file.json.j2
    dest: "{{ jenkins_credentials_file_dest }}"
    mode: "600"
    owner: "{{ jenkins_user }}"

- name: add credentials
  include: execute_jenkins_cli.yaml
  vars:
    jenkins_command_string: "groovy {{ jenkins_credentials_script }}"

- name: clean up
  file: name={{ jenkins_credentials_root }} state=absent

# Create seed job(s)
# Would be better as an include with_vars: jenkins_seed_jobs, but deprecated until Ansible 2.0
- name: create answer_distribution seed job
  include: create_seed_job.yml
  vars:
    seed_job: "{{ jenkins_seed_jobs.answer_distribution }}"
  when: jenkins_seed_jobs.answer_distribution.enabled
  tags:
    - create-answer-distribution-seed-job
    - create-seed-job

- name: create import_enrollments seed job
  include: create_seed_job.yml
  vars:
    seed_job: "{{ jenkins_seed_jobs.import_enrollments }}"
  when: jenkins_seed_jobs.import_enrollments.enabled
  tags:
    - create-seed-job

- name: create course_activity seed job
  include: create_seed_job.yml
  vars:
    seed_job: "{{ jenkins_seed_jobs.course_activity }}"
  when: jenkins_seed_jobs.course_activity.enabled
  tags:
    - create-seed-job

- name: create all_video seed job
  include: create_seed_job.yml
  vars:
    seed_job: "{{ jenkins_seed_jobs.all_video }}"
  when: jenkins_seed_jobs.all_video.enabled
  tags:
    - create-seed-job

- name: create enroll_by_country seed job
  include: create_seed_job.yml
  vars:
    seed_job: "{{ jenkins_seed_jobs.enroll_by_country }}"
  when: jenkins_seed_jobs.enroll_by_country.enabled
  tags:
    - create-seed-job
