---
- include: _auth_realm.yaml

# Unconditionally restart jenkins, this has two side-effects:
# 1. Jenkins uses new auth realm
# 2. We guarantee that jenkins is started (this is not certain
#    as Jenkins is started by handlers from jenkins_master,
#    these handlers are launched after this role.

- name: restart Jenkins
  service: name=jenkins state=restarted

- include: _add_credentials.yaml

- name: create seed job
  include: _create_seed_job.yaml
  vars:
    job_name: "{{ jenkins_seed_job.name }}"
    job: "{{ jenkins_seed_job }}"

