---

# Stateless app server configuration, designed to be used with external mysql
# and mongodb services.
# TODO: use external rabbitmq and elasticsearch as well

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True

  vars:
    migrate_db: 'yes'
    EDXAPP_NO_PREREQ_INSTALL: '0'  # Ensure that dependencies are installed
    EDXAPP_LMS_NGINX_PORT: '80'
    SANDBOX_ENABLE_ECOMMERCE: False  # Disable ecommerce by default

  roles:

    # Server setup
    - swapfile
    - memcache

    # RabbitMQ (TODO: remove this)
    - role: rabbitmq
      rabbitmq_ip: 127.0.0.1

    # Elasticsearch (TODO: remove this)
    - oraclejdk
    - elasticsearch

    # Nginx reverse proxy
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms

    # Main EdX application
    # https://github.com/edx/edx-platform
    - role: edxapp
      celery_worker: True
    - edxapp

    # Discussion forums
    # https://github.com/edx/cs_comments_service
    - forum

    # Notifications service
    # https://github.com/edx/notifier
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: '5'

    # XQueue interface for communicating with external grader services
    # https://github.com/edx/xqueue
    - role: xqueue
      update_users: True

    # Certificate generation
    # https://github.com/edx/edx-certificates
    - certs

    # Ecommerce (optional)
    # https://github.com/edx/ecommerce
    - role: nginx
      nginx_sites:
      - ecommerce
      when: SANDBOX_ENABLE_ECOMMERCE
    - role: ecommerce
      when: SANDBOX_ENABLE_ECOMMERCE
    - role: ecomworker
      when: SANDBOX_ENABLE_ECOMMERCE

    # Optional extras
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
