---

# Sets up server with edx app that can be deployed behind an ELB.

- name: Bootstrap instance(s)
  hosts: app
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: app
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
  roles:
    - role: swapfile
      SWAPFILE_SIZE: 4GB
    - aws
    - security
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms
    - role: nginx
      nginx_sites:
      - ecommerce
      when: SANDBOX_ENABLE_ECOMMERCE
    - role: edxapp
      celery_worker: True
    - edxapp
    - role: ecommerce
      when: SANDBOX_ENABLE_ECOMMERCE
    - role: ecomworker
      when: SANDBOX_ENABLE_ECOMMERCE
    - oauth_client_setup
    - oraclejdk
    - forum
    - role: discovery
      when: SANDBOX_ENABLE_DISCOVERY
    - notifier
    - role: xqueue
      update_users: True
    - certs
    - edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ''
