---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
# Defaults for role go-agent-docker-server
#

# key for go-agents to autoregister with the go-server
GO_SERVER_AUTO_REGISTER_KEY: "dev-only-override-this-key"
GO_AGENT_DOCKER_RESOURCES: "tubular,python"
GO_AGENT_DOCKER_ENVIRONMENT: "sandbox"
GO_AGENT_DOCKER_CONF_HOME: "/tmp/go-agent/conf"